/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AddModelDialog: typeof import('./src/components/AddModelDialog/index.vue')['default']
    EditModelDialog: typeof import('./src/components/EditModelDialog/index.vue')['default']
    ErrorLogDrawer: typeof import('./src/components/ErrorLogDrawer/index.vue')['default']
    ImportConflictDialog: typeof import('./src/components/ImportConflictDialog/index.vue')['default']
    LoginDialog: typeof import('./src/components/LoginDialog/index.vue')['default']
    McpRecordDialog: typeof import('./src/components/McpRecordDialog/index.vue')['default']
    MemoryCard: typeof import('./src/components/MemoryCard/index.vue')['default']
    MemoryDetailDialog: typeof import('./src/components/MemoryDetailDialog/index.vue')['default']
    ModelCard: typeof import('./src/components/ModelCard/index.vue')['default']
    RequestLogDrawer: typeof import('./src/components/RequestLogDrawer/index.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SettingsDialog: typeof import('./src/components/SettingsDialog/index.vue')['default']
    TokenLineChart: typeof import('./src/components/TokenLineChart/index.vue')['default']
  }
}
