/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AddModelDialog: typeof import('./src/components/AddModelDialog/index.vue')['default']
    EditModelDialog: typeof import('./src/components/EditModelDialog/index.vue')['default']
    ErrorLogDrawer: typeof import('./src/components/ErrorLogDrawer/index.vue')['default']
    ImportConflictDialog: typeof import('./src/components/ImportConflictDialog/index.vue')['default']
    LoginDialog: typeof import('./src/components/LoginDialog/index.vue')['default']
    McpRecordDialog: typeof import('./src/components/McpRecordDialog/index.vue')['default']
    ModelCard: typeof import('./src/components/ModelCard/index.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SettingsDialog: typeof import('./src/components/SettingsDialog/index.vue')['default']
    TokenLineChart: typeof import('./src/components/TokenLineChart/index.vue')['default']
    VanActionSheet: typeof import('vant/es')['ActionSheet']
    VanButton: typeof import('vant/es')['Button']
    VanCell: typeof import('vant/es')['Cell']
    VanCellGroup: typeof import('vant/es')['CellGroup']
    VanDialog: typeof import('vant/es')['Dialog']
    VanEmpty: typeof import('vant/es')['Empty']
    VanField: typeof import('vant/es')['Field']
    VanIcon: typeof import('vant/es')['Icon']
    VanImage: typeof import('vant/es')['Image']
    VanLoading: typeof import('vant/es')['Loading']
    VanNavBar: typeof import('vant/es')['NavBar']
    VanPicker: typeof import('vant/es')['Picker']
    VanPopup: typeof import('vant/es')['Popup']
    VanPullRefresh: typeof import('vant/es')['PullRefresh']
    VanTag: typeof import('vant/es')['Tag']
  }
}
